version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      # - ./src:/var/www/html  # PHPファイル用のマウント
      - .:/var/www/html  # project root directory をPHPのルートとしてマウント
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini  # 大きなファイルをアップロードするためのPHP設定ファイルをマウント
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0  # MySQLの8バージョンのイメージを使用
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    restart: always  # サービスが停止した場合に常に再起動
    volumes:
      - ./db/db-data:/var/lib/mysql  # MySQLデータベースのボリュームの保存先
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
